add require "active_support/all"
tlist.rb:12:in `<main>': undefined method `find_zone!' for Time:Class (NoMethodError)

https://qiita.com/hidarikikineko/items/e99f0c939bbef1e6e7b5